const FeedbackTag = require('../models/FeedbackTag');
const IntroductionTag = require('../models/IntroductionTag');
const ResourcesTag = require('../models/ResourcesTag');

const newFeedbackTag1 = new FeedbackTag({ name: 'Hiring' });
const newFeedbackTag2 = new FeedbackTag({ name: 'Marketing' });
const newFeedbackTag3 = new FeedbackTag({ name: 'Management' });
const newFeedbackTag4 = new FeedbackTag({ name: 'Sales' });
const newFeedbackTag5 = new FeedbackTag({ name: 'Interview' });
const newFeedbackTag6 = new FeedbackTag({ name: 'AdWords' });
const newFeedbackTag7 = new FeedbackTag({ name: 'Leading' });
const newFeedbackTag8 = new FeedbackTag({ name: 'Retention' });
const newFeedbackTag9 = new FeedbackTag({ name: 'Culture' });
const newFeedbackTag10 = new FeedbackTag({ name: 'Startup' });
const newFeedbackTag11 = new FeedbackTag({ name: 'SaaS metrics' });
const newFeedbackTag12 = new FeedbackTag({ name: 'Product Direction' });
const newFeedbackTag13 = new FeedbackTag({ name: 'Landing Pages' });
const newFeedbackTag14 = new FeedbackTag({ name: 'Business Strategy' });
const newFeedbackTag15 = new FeedbackTag({ name: 'Leadership' });
const newFeedbackTag16 = new FeedbackTag({ name: 'Software Testing' });
const newFeedbackTag17 = new FeedbackTag({ name: 'Public speaking' });
const newFeedbackTag18 = new FeedbackTag({ name: 'Motivating' });
const newFeedbackTag19 = new FeedbackTag({ name: 'Mind Mapping' });
const newFeedbackTag20 = new FeedbackTag({ name: 'SEO OnPage' });
const newFeedbackTag21 = new FeedbackTag({ name: 'SEO OffPage' });
const newFeedbackTag22 = new FeedbackTag({ name: 'Competition Research' });
const newFeedbackTag23 = new FeedbackTag({ name: 'Brand Building' });
const newFeedbackTag24 = new FeedbackTag({ name: 'Brand Monitoring' });
const newFeedbackTag25 = new FeedbackTag({ name: 'Google AdWords' });
const newFeedbackTag26 = new FeedbackTag({ name: 'Adobe InDesign' });
const newFeedbackTag27 = new FeedbackTag({ name: 'Illustrator' });
const newFeedbackTag28 = new FeedbackTag({ name: 'PhotoShop' });
const newFeedbackTag29 = new FeedbackTag({ name: 'Android apps' });
const newFeedbackTag30 = new FeedbackTag({ name: 'Ruby on Rails' });
const newFeedbackTag31 = new FeedbackTag({ name: 'Mobile UX' });
const newFeedbackTag32 = new FeedbackTag({ name: 'Piano' });
const newFeedbackTag33 = new FeedbackTag({ name: 'Software Architecture' });
const newFeedbackTag34 = new FeedbackTag({ name: 'Crypto Project Review' });
const newFeedbackTag35 = new FeedbackTag({ name: 'Product RoadMap' });
const newFeedbackTag36 = new FeedbackTag({ name: 'Programming' });
const newFeedbackTag37 = new FeedbackTag({ name: 'Code Review' });
const newFeedbackTag38 = new FeedbackTag({ name: 'Software Architecture Review' });
const newFeedbackTag39 = new FeedbackTag({ name: 'Information Security' });
const newFeedbackTag40 = new FeedbackTag({ name: 'Threat Modeling' });
const newFeedbackTag41 = new FeedbackTag({ name: 'Compliance' });
const newFeedbackTag42 = new FeedbackTag({ name: 'Engineering Processes' });
const newFeedbackTag43 = new FeedbackTag({ name: 'Business Analytics' });
const newFeedbackTag44 = new FeedbackTag({ name: 'Data Visualization' });
const newFeedbackTag45 = new FeedbackTag({ name: 'Workflows' });
const newFeedbackTag46 = new FeedbackTag({ name: 'Product Design' });
const newFeedbackTag47 = new FeedbackTag({ name: 'BS Detection in SaaS' });
const newFeedbackTag48 = new FeedbackTag({ name: 'Post-Startup' });
const newFeedbackTag49 = new FeedbackTag({ name: 'Career Choices Mindfulness' });
const newFeedbackTag50 = new FeedbackTag({ name: 'Vipassana' });
const newFeedbackTag51 = new FeedbackTag({ name: 'Django Code' });
const newFeedbackTag52 = new FeedbackTag({ name: 'Algorithms' });
const newFeedbackTag53 = new FeedbackTag({ name: 'Facebook' });
const newFeedbackTag54 = new FeedbackTag({ name: 'Bullshit Detection' });
const newFeedbackTag55 = new FeedbackTag({ name: 'Startup Ideas' });
const newFeedbackTag56 = new FeedbackTag({ name: 'BlockChain' });
const newFeedbackTag57 = new FeedbackTag({ name: 'UX Design' });
const newFeedbackTag58 = new FeedbackTag({ name: 'Psychology' });
const newFeedbackTag59 = new FeedbackTag({ name: 'Digital Product Strategy' });
const newFeedbackTag60 = new FeedbackTag({ name: 'Video at Scale' });
const newFeedbackTag61 = new FeedbackTag({ name: 'Video DRM' });
const newFeedbackTag62 = new FeedbackTag({ name: 'CDN' });
const newFeedbackTag63 = new FeedbackTag({ name: 'Encryptions' });
const newFeedbackTag64 = new FeedbackTag({ name: 'Scaling Infrastructure' });
const newFeedbackTag65 = new FeedbackTag({ name: 'Hybrid Cloud Strategy' });
const newFeedbackTag66 = new FeedbackTag({ name: 'NLP' });
const newFeedbackTag67 = new FeedbackTag({ name: 'Conversion Optimisation' });
const newFeedbackTag68 = new FeedbackTag({ name: 'JavaScript' });
const newFeedbackTag69 = new FeedbackTag({ name: 'MVP' });
const newFeedbackTag70 = new FeedbackTag({ name: 'Mobile Design' });
const newFeedbackTag71 = new FeedbackTag({ name: 'Product Management' });
const newFeedbackTag72 = new FeedbackTag({ name: 'Complex Technology' });
const newFeedbackTag73 = new FeedbackTag({ name: 'Distributed System' });
const newFeedbackTag74 = new FeedbackTag({ name: 'AI/ML' });
const newFeedbackTag75 = new FeedbackTag({ name: 'Databases Infrastructure Software' });
const newFeedbackTag76 = new FeedbackTag({ name: 'First-time Startup' });
const newFeedbackTag77 = new FeedbackTag({ name: 'Dos/DONTs' });
const newFeedbackTag78 = new FeedbackTag({ name: 'Techie Career Advice' });
const newFeedbackTag79 = new FeedbackTag({ name: 'Machine Learning' });
const newFeedbackTag80 = new FeedbackTag({ name: 'Careers' });
const newFeedbackTag81 = new FeedbackTag({ name: 'Mindfulness' });
const newFeedbackTag82 = new FeedbackTag({ name: 'Business Models' });
const newFeedbackTag83 = new FeedbackTag({ name: 'Team Hiring' });
const newFeedbackTag84 = new FeedbackTag({ name: 'Food n Beverage' });
const newFeedbackTag85 = new FeedbackTag({ name: 'Ruby' });
const newFeedbackTag86 = new FeedbackTag({ name: 'Interviewing Advice' });
const newFeedbackTag87 = new FeedbackTag({ name: 'API Design' });
const newFeedbackTag88 = new FeedbackTag({ name: 'Operations' });
const newFeedbackTag89 = new FeedbackTag({ name: 'Data Engineering' });
const newFeedbackTag90 = new FeedbackTag({ name: 'Information Retrieval' });
const newFeedbackTag91 = new FeedbackTag({ name: 'Ways to Improve a Web-page' });
const newFeedbackTag92 = new FeedbackTag({ name: 'User Testing' });
const newFeedbackTag93 = new FeedbackTag({ name: 'Product-Specifically' });
const newFeedbackTag94 = new FeedbackTag({ name: 'Machine Learning Problems' });
const newFeedbackTag95 = new FeedbackTag({ name: 'Managing Culture' });
const newFeedbackTag96 = new FeedbackTag({ name: 'Product Design' });
const newFeedbackTag97 = new FeedbackTag({ name: 'Feedback on Project' });
const newFeedbackTag98 = new FeedbackTag({ name: 'People' });
const newFeedbackTag99 = new FeedbackTag({ name: 'UX Critiques' });
const newFeedbackTag100 = new FeedbackTag({ name: 'Tech Architecture' });
const newFeedbackTag101 = new FeedbackTag({ name: 'Business Process' });
const newFeedbackTag102 = new FeedbackTag({ name: 'Payments' });
const newFeedbackTag103 = new FeedbackTag({ name: 'Customer Interviews' });
const newFeedbackTag104 = new FeedbackTag({ name: 'Idea Validation' });
const newFeedbackTag105 = new FeedbackTag({ name: 'Lean' });
const newFeedbackTag106 = new FeedbackTag({ name: 'User Psychology' });
const newFeedbackTag107 = new FeedbackTag({ name: 'Gamification' });
const newFeedbackTag108 = new FeedbackTag({ name: 'Org Design' });
const newFeedbackTag109 = new FeedbackTag({ name: 'Accelerated Learning' });
const newFeedbackTag110 = new FeedbackTag({ name: 'Mechanical System' });
const newFeedbackTag111 = new FeedbackTag({ name: 'Hardware' });
const newFeedbackTag112 = new FeedbackTag({ name: 'Automotive' });
const newFeedbackTag113 = new FeedbackTag({ name: 'Manufacturing' });


//  create new IntroductionTags model
const newIntroductionTag1 = new IntroductionTag({ name: 'Startup Founders' });
const newIntroductionTag2 = new IntroductionTag({ name: 'BlockChain Enthusiasts' });
const newIntroductionTag3 = new IntroductionTag({ name: 'Marketers' });
const newIntroductionTag4 = new IntroductionTag({ name: 'SMB CXOs' });
const newIntroductionTag5 = new IntroductionTag({ name: 'Sales' });
const newIntroductionTag6 = new IntroductionTag({ name: 'US Engineers' });
const newIntroductionTag7 = new IntroductionTag({ name: 'Founders' });
const newIntroductionTag8 = new IntroductionTag({ name: 'Investors' });
const newIntroductionTag9 = new IntroductionTag({ name: 'Software Tester' });
const newIntroductionTag10 = new IntroductionTag({ name: 'Design Community' });
const newIntroductionTag11 = new IntroductionTag({ name: 'Germany Companys' });
const newIntroductionTag12 = new IntroductionTag({ name: 'German SEOs' });
const newIntroductionTag13 = new IntroductionTag({ name: 'Ruby Developers' });
const newIntroductionTag14 = new IntroductionTag({ name: 'ED Tech Founders' });
const newIntroductionTag15 = new IntroductionTag({ name: 'Android Developers' });
const newIntroductionTag16 = new IntroductionTag({ name: 'Factory Owners' });
const newIntroductionTag17 = new IntroductionTag({ name: 'Programmers' });
const newIntroductionTag18 = new IntroductionTag({ name: 'Executives' });
const newIntroductionTag19 = new IntroductionTag({ name: 'Doctors' });
const newIntroductionTag20 = new IntroductionTag({ name: 'Software Architecture' });
const newIntroductionTag21 = new IntroductionTag({ name: 'Engineers' });
const newIntroductionTag22 = new IntroductionTag({ name: 'IT Sector' });
const newIntroductionTag23 = new IntroductionTag({ name: 'Accelerators' });
const newIntroductionTag24 = new IntroductionTag({ name: 'Developer' });
const newIntroductionTag25 = new IntroductionTag({ name: 'Facebook advertisers' });
const newIntroductionTag26 = new IntroductionTag({ name: 'Marwari People' });
const newIntroductionTag27 = new IntroductionTag({ name: 'Startup Founder' });
const newIntroductionTag28 = new IntroductionTag({ name: 'BlockChain Folks' });
const newIntroductionTag29 = new IntroductionTag({ name: 'Thinkers' });
const newIntroductionTag30 = new IntroductionTag({ name: 'Entrepreneur' });
const newIntroductionTag31 = new IntroductionTag({ name: 'Marketing Sales' });
const newIntroductionTag32 = new IntroductionTag({ name: 'Founder and Devs' });
const newIntroductionTag33 = new IntroductionTag({ name: 'Product Managers' });
const newIntroductionTag34 = new IntroductionTag({ name: 'Designers' });
const newIntroductionTag35 = new IntroductionTag({ name: 'Senior Techies' });
const newIntroductionTag36 = new IntroductionTag({ name: 'Industry Leaders' });
const newIntroductionTag37 = new IntroductionTag({ name: 'Angel Investors' });
const newIntroductionTag38 = new IntroductionTag({ name: 'Startup EcoSystem' });
const newIntroductionTag39 = new IntroductionTag({ name: 'Machine Learning' });
const newIntroductionTag40 = new IntroductionTag({ name: 'Enthusiasts' });
const newIntroductionTag41 = new IntroductionTag({ name: 'Kagglers' });
const newIntroductionTag42 = new IntroductionTag({ name: 'Professionals' });
const newIntroductionTag43 = new IntroductionTag({ name: 'Ecommerce Professionals' });
const newIntroductionTag44 = new IntroductionTag({ name: 'Web Developers' });
const newIntroductionTag45 = new IntroductionTag({ name: 'Budding Artists' });
const newIntroductionTag46 = new IntroductionTag({ name: 'VCs' });
const newIntroductionTag47 = new IntroductionTag({ name: 'Mentors' });
const newIntroductionTag48 = new IntroductionTag({ name: 'SAP' });
const newIntroductionTag49 = new IntroductionTag({ name: 'People in Telecom' });
const newIntroductionTag50 = new IntroductionTag({ name: 'Big Data' });
const newIntroductionTag51 = new IntroductionTag({ name: 'Self-Funded Founders' });
const newIntroductionTag52 = new IntroductionTag({ name: 'Growth Hackers' });
const newIntroductionTag53 = new IntroductionTag({ name: 'Marketers' });
const newIntroductionTag54 = new IntroductionTag({ name: 'Bankers' });
const newIntroductionTag55 = new IntroductionTag({ name: 'Marketers' });
const newIntroductionTag56 = new IntroductionTag({ name: 'Communities' });
const newIntroductionTag57 = new IntroductionTag({ name: 'CMO of B2B' });
const newIntroductionTag58 = new IntroductionTag({ name: 'Manufacturing' });
const newIntroductionTag59 = new IntroductionTag({ name: 'Data Scientist' });
const newIntroductionTag60 = new IntroductionTag({ name: 'Software Engineers' });
const newIntroductionTag61 = new IntroductionTag({ name: 'CXOs' });


const newResourcesTag1 = new ResourcesTag({ name: 'Management Books' });
const newResourcesTag2 = new ResourcesTag({ name: 'BlockChain Projects' });
const newResourcesTag3 = new ResourcesTag({ name: 'Articles' });
const newResourcesTag4 = new ResourcesTag({ name: 'Psychology' });
const newResourcesTag5 = new ResourcesTag({ name: 'Economics Papers' });
const newResourcesTag6 = new ResourcesTag({ name: 'Health' });
const newResourcesTag7 = new ResourcesTag({ name: 'Energy' });
const newResourcesTag8 = new ResourcesTag({ name: 'Astronomy' });
const newResourcesTag9 = new ResourcesTag({ name: 'Physics' });
const newResourcesTag10 = new ResourcesTag({ name: 'Space' });
const newResourcesTag11 = new ResourcesTag({ name: 'Creating Great Company Culture' });
const newResourcesTag12 = new ResourcesTag({ name: 'Software Testing' });
const newResourcesTag13 = new ResourcesTag({ name: 'Blogs' });
const newResourcesTag14 = new ResourcesTag({ name: 'My Handcrafts' });
const newResourcesTag15 = new ResourcesTag({ name: 'Marketing Feedly' });
const newResourcesTag16 = new ResourcesTag({ name: 'Piano Tutorials' });
const newResourcesTag17 = new ResourcesTag({ name: 'Marketing' });
const newResourcesTag18 = new ResourcesTag({ name: 'Development' });
const newResourcesTag19 = new ResourcesTag({ name: 'Programming' });
const newResourcesTag20 = new ResourcesTag({ name: 'Mathematics' });
const newResourcesTag21 = new ResourcesTag({ name: 'AI' });
const newResourcesTag22 = new ResourcesTag({ name: 'Machine Learning' });
const newResourcesTag23 = new ResourcesTag({ name: 'BlockChain' });
const newResourcesTag24 = new ResourcesTag({ name: 'Software Engineering' });
const newResourcesTag25 = new ResourcesTag({ name: 'Technical Leadership' });
const newResourcesTag26 = new ResourcesTag({ name: 'Information Security' });
const newResourcesTag27 = new ResourcesTag({ name: 'Machine Learning' });
const newResourcesTag28 = new ResourcesTag({ name: 'MOOC' });
const newResourcesTag29 = new ResourcesTag({ name: 'Startup Ideas' });
const newResourcesTag30 = new ResourcesTag({ name: 'Non-Fiction Book' });
const newResourcesTag31 = new ResourcesTag({ name: 'Management' });
const newResourcesTag32 = new ResourcesTag({ name: 'Self-improvement' });
const newResourcesTag33 = new ResourcesTag({ name: 'Books' });
const newResourcesTag34 = new ResourcesTag({ name: 'Biographies' });
const newResourcesTag35 = new ResourcesTag({ name: 'PMF' });
const newResourcesTag36 = new ResourcesTag({ name: 'GTM' });
const newResourcesTag37 = new ResourcesTag({ name: 'SaaS Mindfulness' });
const newResourcesTag38 = new ResourcesTag({ name: 'Business Books' });
const newResourcesTag39 = new ResourcesTag({ name: 'Social Anxiety' });
const newResourcesTag40 = new ResourcesTag({ name: 'Human Behaviour' });
const newResourcesTag41 = new ResourcesTag({ name: 'Digital World' });
const newResourcesTag42 = new ResourcesTag({ name: 'Video DRM' });
const newResourcesTag43 = new ResourcesTag({ name: 'oudCl' });
const newResourcesTag44 = new ResourcesTag({ name: 'LeaderShip' });
const newResourcesTag45 = new ResourcesTag({ name: 'PMF' });
const newResourcesTag46 = new ResourcesTag({ name: 'PCF' });
const newResourcesTag47 = new ResourcesTag({ name: 'Growth' });
const newResourcesTag48 = new ResourcesTag({ name: 'India Specific Problems' });
const newResourcesTag49 = new ResourcesTag({ name: 'Education' });
const newResourcesTag50 = new ResourcesTag({ name: 'Technology' });
const newResourcesTag51 = new ResourcesTag({ name: 'Data Science' });
const newResourcesTag52 = new ResourcesTag({ name: 'Differential Programming' });
const newResourcesTag53 = new ResourcesTag({ name: 'Drones' });
const newResourcesTag54 = new ResourcesTag({ name: 'Comp Vision' });
const newResourcesTag55 = new ResourcesTag({ name: 'Behavioral Economics' });
const newResourcesTag56 = new ResourcesTag({ name: 'Payments' });
const newResourcesTag57 = new ResourcesTag({ name: 'Next Billion' });
const newResourcesTag58 = new ResourcesTag({ name: 'Users' });
const newResourcesTag59 = new ResourcesTag({ name: 'Programming' });
const newResourcesTag60 = new ResourcesTag({ name: 'Ruby' });
const newResourcesTag61 = new ResourcesTag({ name: 'Ruby on Rails' });
const newResourcesTag62 = new ResourcesTag({ name: 'Web Application' });
const newResourcesTag63 = new ResourcesTag({ name: 'API Development' });
const newResourcesTag64 = new ResourcesTag({ name: 'Consumer Psychology' });
const newResourcesTag65 = new ResourcesTag({ name: 'Product Building' });
const newResourcesTag66 = new ResourcesTag({ name: 'Mindfulness' });
const newResourcesTag67 = new ResourcesTag({ name: 'Users Psychology' });
const newResourcesTag68 = new ResourcesTag({ name: 'Deep Learning' });
const newResourcesTag69 = new ResourcesTag({ name: 'Python' });
const newResourcesTag70 = new ResourcesTag({ name: 'AngularJS' });
const newResourcesTag71 = new ResourcesTag({ name: 'Engineering Team' });
const newResourcesTag72 = new ResourcesTag({ name: 'competition' });
const newResourcesTag73 = new ResourcesTag({ name: 'Beginner Tech Course' });
const newResourcesTag74 = new ResourcesTag({ name: 'Design' });
const newResourcesTag75 = new ResourcesTag({ name: 'Shared Mobility' });
const newResourcesTag76 = new ResourcesTag({ name: 'Politics' });
const newResourcesTag77 = new ResourcesTag({ name: 'Games' });
const newResourcesTag78 = new ResourcesTag({ name: 'Recently Incentive Systems' });
const newResourcesTag79 = new ResourcesTag({ name: 'Open-Source Software' });
const newResourcesTag80 = new ResourcesTag({ name: 'Best Practice' });
const newResourcesTag81 = new ResourcesTag({ name: 'Web Dev' });
const newResourcesTag82 = new ResourcesTag({ name: '' });
const newResourcesTag83 = new ResourcesTag({ name: 'ML' });
const newResourcesTag84 = new ResourcesTag({ name: 'product Dev' });
const newResourcesTag85 = new ResourcesTag({ name: 'Arsenal Football Club' });
const newResourcesTag86 = new ResourcesTag({ name: 'User OnBoarding' });
const newResourcesTag87 = new ResourcesTag({ name: 'Productivity' });
const newResourcesTag88 = new ResourcesTag({ name: 'Parenting' });
const newResourcesTag89 = new ResourcesTag({ name: 'Reddit' });
const newResourcesTag90 = new ResourcesTag({ name: 'Researching' });

function saveAllFeedbackTags() {
  newFeedbackTag1.save();
  newFeedbackTag2.save();
  newFeedbackTag3.save();
  newFeedbackTag4.save();
  newFeedbackTag5.save();
  newFeedbackTag6.save();
  newFeedbackTag7.save();
  newFeedbackTag8.save();
  newFeedbackTag9.save();
  newFeedbackTag10.save();
  newFeedbackTag11.save();
  newFeedbackTag12.save();
  newFeedbackTag13.save();
  newFeedbackTag14.save();
  newFeedbackTag15.save();
  newFeedbackTag16.save();
  newFeedbackTag17.save();
  newFeedbackTag18.save();
  newFeedbackTag19.save();
  newFeedbackTag20.save();
  newFeedbackTag21.save();
  newFeedbackTag22.save();
  newFeedbackTag23.save();
  newFeedbackTag24.save();
  newFeedbackTag25.save();
  newFeedbackTag26.save();
  newFeedbackTag27.save();
  newFeedbackTag28.save();
  newFeedbackTag29.save();
  newFeedbackTag30.save();
  newFeedbackTag31.save();
  newFeedbackTag32.save();
  newFeedbackTag33.save();
  newFeedbackTag34.save();
  newFeedbackTag35.save();
  newFeedbackTag36.save();
  newFeedbackTag37.save();
  newFeedbackTag38.save();
  newFeedbackTag39.save();
  newFeedbackTag40.save();
  newFeedbackTag41.save();
  newFeedbackTag42.save();
  newFeedbackTag43.save();
  newFeedbackTag44.save();
  newFeedbackTag45.save();
  newFeedbackTag46.save();
  newFeedbackTag47.save();
  newFeedbackTag48.save();
  newFeedbackTag49.save();
  newFeedbackTag50.save();
  newFeedbackTag51.save();
  newFeedbackTag52.save();
  newFeedbackTag53.save();
  newFeedbackTag54.save();
  newFeedbackTag55.save();
  newFeedbackTag56.save();
  newFeedbackTag57.save();
  newFeedbackTag58.save();
  newFeedbackTag59.save();
  newFeedbackTag60.save();
  newFeedbackTag61.save();
  newFeedbackTag62.save();
  newFeedbackTag63.save();
  newFeedbackTag64.save();
  newFeedbackTag65.save();
  newFeedbackTag66.save();
  newFeedbackTag67.save();
  newFeedbackTag68.save();
  newFeedbackTag69.save();
  newFeedbackTag70.save();
  newFeedbackTag71.save();
  newFeedbackTag72.save();
  newFeedbackTag73.save();
  newFeedbackTag74.save();
  newFeedbackTag75.save();
  newFeedbackTag76.save();
  newFeedbackTag77.save();
  newFeedbackTag78.save();
  newFeedbackTag79.save();
  newFeedbackTag80.save();
  newFeedbackTag81.save();
  newFeedbackTag82.save();
  newFeedbackTag83.save();
  newFeedbackTag84.save();
  newFeedbackTag85.save();
  newFeedbackTag86.save();
  newFeedbackTag87.save();
  newFeedbackTag88.save();
  newFeedbackTag89.save();
  newFeedbackTag90.save();
  newFeedbackTag91.save();
  newFeedbackTag92.save();
  newFeedbackTag93.save();
  newFeedbackTag94.save();
  newFeedbackTag95.save();
  newFeedbackTag96.save();
  newFeedbackTag97.save();
  newFeedbackTag98.save();
  newFeedbackTag99.save();
  newFeedbackTag100.save();
  newFeedbackTag101.save();
  newFeedbackTag102.save();
  newFeedbackTag103.save();
  newFeedbackTag104.save();
  newFeedbackTag105.save();
  newFeedbackTag106.save();
  newFeedbackTag107.save();
  newFeedbackTag108.save();
  newFeedbackTag109.save();
  newFeedbackTag110.save();
  newFeedbackTag111.save();
  newFeedbackTag112.save();
  newFeedbackTag113.save();
}

function saveAllIntroductionTags() {
  newIntroductionTag1.save();
  newIntroductionTag2.save();
  newIntroductionTag3.save();
  newIntroductionTag4.save();
  newIntroductionTag5.save();
  newIntroductionTag6.save();
  newIntroductionTag7.save();
  newIntroductionTag8.save();
  newIntroductionTag9.save();
  newIntroductionTag10.save();
  newIntroductionTag11.save();
  newIntroductionTag12.save();
  newIntroductionTag13.save();
  newIntroductionTag14.save();
  newIntroductionTag15.save();
  newIntroductionTag16.save();
  newIntroductionTag17.save();
  newIntroductionTag18.save();
  newIntroductionTag19.save();
  newIntroductionTag20.save();
  newIntroductionTag21.save();
  newIntroductionTag22.save();
  newIntroductionTag23.save();
  newIntroductionTag24.save();
  newIntroductionTag25.save();
  newIntroductionTag26.save();
  newIntroductionTag27.save();
  newIntroductionTag28.save();
  newIntroductionTag29.save();
  newIntroductionTag30.save();
  newIntroductionTag31.save();
  newIntroductionTag32.save();
  newIntroductionTag33.save();
  newIntroductionTag34.save();
  newIntroductionTag35.save();
  newIntroductionTag36.save();
  newIntroductionTag37.save();
  newIntroductionTag38.save();
  newIntroductionTag39.save();
  newIntroductionTag40.save();
  newIntroductionTag41.save();
  newIntroductionTag42.save();
  newIntroductionTag43.save();
  newIntroductionTag44.save();
  newIntroductionTag45.save();
  newIntroductionTag46.save();
  newIntroductionTag47.save();
  newIntroductionTag48.save();
  newIntroductionTag49.save();
  newIntroductionTag50.save();
  newIntroductionTag51.save();
  newIntroductionTag52.save();
  newIntroductionTag53.save();
  newIntroductionTag54.save();
  newIntroductionTag55.save();
  newIntroductionTag56.save();
  newIntroductionTag57.save();
  newIntroductionTag58.save();
  newIntroductionTag59.save();
  newIntroductionTag60.save();
  newIntroductionTag61.save();
}


function saveAllResourcesTags() {
  newResourcesTag1.save();
  newResourcesTag2.save();
  newResourcesTag3.save();
  newResourcesTag4.save();
  newResourcesTag5.save();
  newResourcesTag6.save();
  newResourcesTag7.save();
  newResourcesTag8.save();
  newResourcesTag9.save();
  newResourcesTag10.save();
  newResourcesTag11.save();
  newResourcesTag12.save();
  newResourcesTag13.save();
  newResourcesTag14.save();
  newResourcesTag15.save();
  newResourcesTag16.save();
  newResourcesTag17.save();
  newResourcesTag18.save();
  newResourcesTag19.save();
  newResourcesTag20.save();
  newResourcesTag21.save();
  newResourcesTag22.save();
  newResourcesTag23.save();
  newResourcesTag24.save();
  newResourcesTag25.save();
  newResourcesTag26.save();
  newResourcesTag27.save();
  newResourcesTag28.save();
  newResourcesTag29.save();
  newResourcesTag30.save();
  newResourcesTag31.save();
  newResourcesTag32.save();
  newResourcesTag33.save();
  newResourcesTag34.save();
  newResourcesTag35.save();
  newResourcesTag36.save();
  newResourcesTag37.save();
  newResourcesTag38.save();
  newResourcesTag39.save();
  newResourcesTag40.save();
  newResourcesTag41.save();
  newResourcesTag42.save();
  newResourcesTag43.save();
  newResourcesTag44.save();
  newResourcesTag45.save();
  newResourcesTag46.save();
  newResourcesTag47.save();
  newResourcesTag48.save();
  newResourcesTag49.save();
  newResourcesTag50.save();
  newResourcesTag51.save();
  newResourcesTag52.save();
  newResourcesTag53.save();
  newResourcesTag54.save();
  newResourcesTag55.save();
  newResourcesTag56.save();
  newResourcesTag57.save();
  newResourcesTag58.save();
  newResourcesTag59.save();
  newResourcesTag60.save();
  newResourcesTag61.save();
  newResourcesTag62.save();
  newResourcesTag63.save();
  newResourcesTag64.save();
  newResourcesTag65.save();
  newResourcesTag66.save();
  newResourcesTag67.save();
  newResourcesTag68.save();
  newResourcesTag69.save();
  newResourcesTag70.save();
  newResourcesTag71.save();
  newResourcesTag72.save();
  newResourcesTag73.save();
  newResourcesTag74.save();
  newResourcesTag75.save();
  newResourcesTag76.save();
  newResourcesTag77.save();
  newResourcesTag78.save();
  newResourcesTag79.save();
  newResourcesTag80.save();
  newResourcesTag81.save();
  newResourcesTag82.save();
  newResourcesTag83.save();
  newResourcesTag84.save();
  newResourcesTag85.save();
  newResourcesTag86.save();
  newResourcesTag87.save();
  newResourcesTag88.save();
  newResourcesTag89.save();
  newResourcesTag90.save();
}

module.exports = {
  init: () => {
    ResourcesTag.count((err, number) => {
      if (number === 0) {
        saveAllFeedbackTags();
        saveAllIntroductionTags();
        saveAllResourcesTags();
        // save
      }
    });
  },
};
