const FeedbackTag = require('../models/FeedbackTag');
const IntroductionTag = require('../models/IntroductionTag');
const ResourcesTag = require('../models/ResourcesTag');

const newFeedbackTag1 = new FeedbackTag({ name: 'hiring' });
const newFeedbackTag2 = new FeedbackTag({ name: 'marketing' });
const newFeedbackTag3 = new FeedbackTag({ name: 'management' });
const newFeedbackTag4 = new FeedbackTag({ name: 'sales' });
const newFeedbackTag5 = new FeedbackTag({ name: 'interview' });
const newFeedbackTag6 = new FeedbackTag({ name: 'adwords' });
const newFeedbackTag7 = new FeedbackTag({ name: 'leading' });
const newFeedbackTag8 = new FeedbackTag({ name: 'retention' });
const newFeedbackTag9 = new FeedbackTag({ name: 'culture' });
const newFeedbackTag10 = new FeedbackTag({ name: 'startup' });
const newFeedbackTag11 = new FeedbackTag({ name: 'saaS metrics' });
const newFeedbackTag12 = new FeedbackTag({ name: 'product direction' });
const newFeedbackTag13 = new FeedbackTag({ name: 'landing pages' });
const newFeedbackTag14 = new FeedbackTag({ name: 'business strategy' });
const newFeedbackTag15 = new FeedbackTag({ name: 'leadership' });
const newFeedbackTag16 = new FeedbackTag({ name: 'software testing' });
const newFeedbackTag17 = new FeedbackTag({ name: 'public speaking' });
const newFeedbackTag18 = new FeedbackTag({ name: 'motivating' });
const newFeedbackTag19 = new FeedbackTag({ name: 'mind mapping' });
const newFeedbackTag20 = new FeedbackTag({ name: 'seo onpage' });
const newFeedbackTag21 = new FeedbackTag({ name: 'seo offPage' });
const newFeedbackTag22 = new FeedbackTag({ name: 'competition research' });
const newFeedbackTag23 = new FeedbackTag({ name: 'brand building' });
const newFeedbackTag24 = new FeedbackTag({ name: 'brand monitoring' });
const newFeedbackTag25 = new FeedbackTag({ name: 'google adwords' });
const newFeedbackTag26 = new FeedbackTag({ name: 'adobe Indesign' });
const newFeedbackTag27 = new FeedbackTag({ name: 'illustrator' });
const newFeedbackTag28 = new FeedbackTag({ name: 'photoshop' });
const newFeedbackTag29 = new FeedbackTag({ name: 'android apps' });
const newFeedbackTag30 = new FeedbackTag({ name: 'ruby on rails' });
const newFeedbackTag31 = new FeedbackTag({ name: 'mobile ux' });
const newFeedbackTag32 = new FeedbackTag({ name: 'Piano' });
const newFeedbackTag33 = new FeedbackTag({ name: 'software architecture' });
const newFeedbackTag34 = new FeedbackTag({ name: 'crypto project Review' });
const newFeedbackTag35 = new FeedbackTag({ name: 'product Roadmap' });
const newFeedbackTag36 = new FeedbackTag({ name: 'programming' });
const newFeedbackTag37 = new FeedbackTag({ name: 'code Review' });
const newFeedbackTag38 = new FeedbackTag({ name: 'software architecture review' });
const newFeedbackTag39 = new FeedbackTag({ name: 'Information security' });
const newFeedbackTag40 = new FeedbackTag({ name: 'Threat modeling' });
const newFeedbackTag41 = new FeedbackTag({ name: 'compliance' });
const newFeedbackTag42 = new FeedbackTag({ name: 'engineering processes' });
const newFeedbackTag43 = new FeedbackTag({ name: 'business analytics' });
const newFeedbackTag44 = new FeedbackTag({ name: 'data visualization' });
const newFeedbackTag45 = new FeedbackTag({ name: 'workflows' });
const newFeedbackTag46 = new FeedbackTag({ name: 'product design' });
const newFeedbackTag47 = new FeedbackTag({ name: 'bs detection in sas' });
const newFeedbackTag48 = new FeedbackTag({ name: 'Post-startup' });
const newFeedbackTag49 = new FeedbackTag({ name: 'career choices mindfulness' });
const newFeedbackTag50 = new FeedbackTag({ name: 'vipassana' });
const newFeedbackTag51 = new FeedbackTag({ name: 'django code' });
const newFeedbackTag52 = new FeedbackTag({ name: 'algorithms' });
const newFeedbackTag53 = new FeedbackTag({ name: 'Facebook' });
const newFeedbackTag54 = new FeedbackTag({ name: 'bullshit detection' });
const newFeedbackTag55 = new FeedbackTag({ name: 'startup Ideas' });
const newFeedbackTag56 = new FeedbackTag({ name: 'blockchain' });
const newFeedbackTag57 = new FeedbackTag({ name: 'ux design' });
const newFeedbackTag58 = new FeedbackTag({ name: 'Psychology' });
const newFeedbackTag59 = new FeedbackTag({ name: 'digital product strategy' });
const newFeedbackTag60 = new FeedbackTag({ name: 'video at scale' });
const newFeedbackTag61 = new FeedbackTag({ name: 'video drm' });
const newFeedbackTag62 = new FeedbackTag({ name: 'cdn' });
const newFeedbackTag63 = new FeedbackTag({ name: 'encryptions' });
const newFeedbackTag64 = new FeedbackTag({ name: 'scaling Infrastructure' });
const newFeedbackTag65 = new FeedbackTag({ name: 'hybrid cloud strategy' });
const newFeedbackTag66 = new FeedbackTag({ name: 'nlp' });
const newFeedbackTag67 = new FeedbackTag({ name: 'conversion optimisation' });
const newFeedbackTag68 = new FeedbackTag({ name: 'javascript' });
const newFeedbackTag69 = new FeedbackTag({ name: 'mVP' });
const newFeedbackTag70 = new FeedbackTag({ name: 'mobile design' });
const newFeedbackTag71 = new FeedbackTag({ name: 'product management' });
const newFeedbackTag72 = new FeedbackTag({ name: 'complex Technology' });
const newFeedbackTag73 = new FeedbackTag({ name: 'distributed system' });
const newFeedbackTag74 = new FeedbackTag({ name: 'aI/mL' });
const newFeedbackTag75 = new FeedbackTag({ name: 'databases infrastructure software' });
const newFeedbackTag76 = new FeedbackTag({ name: 'first-time startup' });
const newFeedbackTag77 = new FeedbackTag({ name: 'dos/dONTs' });
const newFeedbackTag78 = new FeedbackTag({ name: 'Techie career advice' });
const newFeedbackTag79 = new FeedbackTag({ name: 'machine learning' });
const newFeedbackTag80 = new FeedbackTag({ name: 'careers' });
const newFeedbackTag81 = new FeedbackTag({ name: 'mindfulness' });
const newFeedbackTag82 = new FeedbackTag({ name: 'business models' });
const newFeedbackTag83 = new FeedbackTag({ name: 'team hiring' });
const newFeedbackTag84 = new FeedbackTag({ name: 'Food n beverage' });
const newFeedbackTag85 = new FeedbackTag({ name: 'ruby' });
const newFeedbackTag86 = new FeedbackTag({ name: 'interviewing advice' });
const newFeedbackTag87 = new FeedbackTag({ name: 'aPI design' });
const newFeedbackTag88 = new FeedbackTag({ name: 'operations' });
const newFeedbackTag89 = new FeedbackTag({ name: 'data engineering' });
const newFeedbackTag90 = new FeedbackTag({ name: 'information Retrieval' });
const newFeedbackTag91 = new FeedbackTag({ name: 'ways to improve a web-page' });
const newFeedbackTag92 = new FeedbackTag({ name: 'user testing' });
const newFeedbackTag93 = new FeedbackTag({ name: 'product-specifically' });
const newFeedbackTag94 = new FeedbackTag({ name: 'machine Learning problems' });
const newFeedbackTag95 = new FeedbackTag({ name: 'managing culture' });
const newFeedbackTag96 = new FeedbackTag({ name: 'product design' });
const newFeedbackTag97 = new FeedbackTag({ name: 'feedback on project' });
const newFeedbackTag98 = new FeedbackTag({ name: 'people' });
const newFeedbackTag99 = new FeedbackTag({ name: 'ux critiques' });
const newFeedbackTag100 = new FeedbackTag({ name: 'tech architecture' });
const newFeedbackTag101 = new FeedbackTag({ name: 'business process' });
const newFeedbackTag102 = new FeedbackTag({ name: 'payments' });
const newFeedbackTag103 = new FeedbackTag({ name: 'customer interviews' });
const newFeedbackTag104 = new FeedbackTag({ name: 'Idea Validation' });
const newFeedbackTag105 = new FeedbackTag({ name: 'Lean' });
const newFeedbackTag106 = new FeedbackTag({ name: 'user psychology' });
const newFeedbackTag107 = new FeedbackTag({ name: 'gamification' });
const newFeedbackTag108 = new FeedbackTag({ name: 'org design' });
const newFeedbackTag109 = new FeedbackTag({ name: 'acelerated Learning' });
const newFeedbackTag110 = new FeedbackTag({ name: 'mechanical system' });
const newFeedbackTag111 = new FeedbackTag({ name: 'hardware' });
const newFeedbackTag112 = new FeedbackTag({ name: 'automotive' });
const newFeedbackTag113 = new FeedbackTag({ name: 'manufacturing' });


//  create new IntroductionTags model
const newIntroductionTag1 = new IntroductionTag({ name: 'startup Founders' });
const newIntroductionTag2 = new IntroductionTag({ name: 'blockchain enthusiasts' });
const newIntroductionTag3 = new IntroductionTag({ name: 'marketers' });
const newIntroductionTag4 = new IntroductionTag({ name: 'smb cXOs' });
const newIntroductionTag5 = new IntroductionTag({ name: 'sales' });
const newIntroductionTag6 = new IntroductionTag({ name: 'us engineers' });
const newIntroductionTag7 = new IntroductionTag({ name: 'Founders' });
const newIntroductionTag8 = new IntroductionTag({ name: 'Investors' });
const newIntroductionTag9 = new IntroductionTag({ name: 'software Tester' });
const newIntroductionTag10 = new IntroductionTag({ name: 'design community' });
const newIntroductionTag11 = new IntroductionTag({ name: 'germany companys' });
const newIntroductionTag12 = new IntroductionTag({ name: 'german seOs' });
const newIntroductionTag13 = new IntroductionTag({ name: 'ruby developers' });
const newIntroductionTag14 = new IntroductionTag({ name: 'ed tech founders' });
const newIntroductionTag15 = new IntroductionTag({ name: 'android developers' });
const newIntroductionTag16 = new IntroductionTag({ name: 'factory owners' });
const newIntroductionTag17 = new IntroductionTag({ name: 'programmers' });
const newIntroductionTag18 = new IntroductionTag({ name: 'executives' });
const newIntroductionTag19 = new IntroductionTag({ name: 'doctors' });
const newIntroductionTag20 = new IntroductionTag({ name: 'software architecture' });
const newIntroductionTag21 = new IntroductionTag({ name: 'engineers' });
const newIntroductionTag22 = new IntroductionTag({ name: 'it sector' });
const newIntroductionTag23 = new IntroductionTag({ name: 'acelerators' });
const newIntroductionTag24 = new IntroductionTag({ name: 'developer' });
const newIntroductionTag25 = new IntroductionTag({ name: 'facebook advertisers' });
const newIntroductionTag26 = new IntroductionTag({ name: 'marwari People' });
const newIntroductionTag27 = new IntroductionTag({ name: 'startup Founder' });
const newIntroductionTag28 = new IntroductionTag({ name: 'blockchain Folks' });
const newIntroductionTag29 = new IntroductionTag({ name: 'Thinkers' });
const newIntroductionTag30 = new IntroductionTag({ name: 'entrepreneur' });
const newIntroductionTag31 = new IntroductionTag({ name: 'marketing sales' });
const newIntroductionTag32 = new IntroductionTag({ name: 'founder and devs' });
const newIntroductionTag33 = new IntroductionTag({ name: 'product managers' });
const newIntroductionTag34 = new IntroductionTag({ name: 'designers' });
const newIntroductionTag35 = new IntroductionTag({ name: 'senior techies' });
const newIntroductionTag36 = new IntroductionTag({ name: 'industry Leaders' });
const newIntroductionTag37 = new IntroductionTag({ name: 'angel Investors' });
const newIntroductionTag38 = new IntroductionTag({ name: 'startup ecosystem' });
const newIntroductionTag39 = new IntroductionTag({ name: 'machine learning' });
const newIntroductionTag40 = new IntroductionTag({ name: 'enthusiasts' });
const newIntroductionTag41 = new IntroductionTag({ name: 'kaglers' });
const newIntroductionTag42 = new IntroductionTag({ name: 'professionals' });
const newIntroductionTag43 = new IntroductionTag({ name: 'ecommerce professionals' });
const newIntroductionTag44 = new IntroductionTag({ name: 'Web developers' });
const newIntroductionTag45 = new IntroductionTag({ name: 'budding artists' });
const newIntroductionTag46 = new IntroductionTag({ name: 'vcs' });
const newIntroductionTag47 = new IntroductionTag({ name: 'mentors' });
const newIntroductionTag48 = new IntroductionTag({ name: 'saP' });
const newIntroductionTag49 = new IntroductionTag({ name: 'People in telecom' });
const newIntroductionTag50 = new IntroductionTag({ name: 'big data' });
const newIntroductionTag51 = new IntroductionTag({ name: 'self-funded founders' });
const newIntroductionTag52 = new IntroductionTag({ name: 'growth hackers' });
const newIntroductionTag53 = new IntroductionTag({ name: 'marketers' });
const newIntroductionTag54 = new IntroductionTag({ name: 'bankers' });
const newIntroductionTag55 = new IntroductionTag({ name: 'marketers' });
const newIntroductionTag56 = new IntroductionTag({ name: 'communities' });
const newIntroductionTag57 = new IntroductionTag({ name: 'cmo of b2b' });
const newIntroductionTag58 = new IntroductionTag({ name: 'manufacturing' });
const newIntroductionTag59 = new IntroductionTag({ name: 'data scientist' });
const newIntroductionTag60 = new IntroductionTag({ name: 'software engineers' });
const newIntroductionTag61 = new IntroductionTag({ name: 'cxOs' });


const newResourcesTag1 = new ResourcesTag({ name: 'management books' });
const newResourcesTag2 = new ResourcesTag({ name: 'blockchain projects' });
const newResourcesTag3 = new ResourcesTag({ name: 'articles' });
const newResourcesTag4 = new ResourcesTag({ name: 'psychology' });
const newResourcesTag5 = new ResourcesTag({ name: 'economics papers' });
const newResourcesTag6 = new ResourcesTag({ name: 'Health' });
const newResourcesTag7 = new ResourcesTag({ name: 'energy' });
const newResourcesTag8 = new ResourcesTag({ name: 'astronomy' });
const newResourcesTag9 = new ResourcesTag({ name: 'physics' });
const newResourcesTag10 = new ResourcesTag({ name: 'space' });
const newResourcesTag11 = new ResourcesTag({ name: 'creating great company culture' });
const newResourcesTag12 = new ResourcesTag({ name: 'software testing' });
const newResourcesTag13 = new ResourcesTag({ name: 'blogs' });
const newResourcesTag14 = new ResourcesTag({ name: 'my handcrafts' });
const newResourcesTag15 = new ResourcesTag({ name: 'marketing feedly' });
const newResourcesTag16 = new ResourcesTag({ name: 'Piano tutorials' });
const newResourcesTag17 = new ResourcesTag({ name: 'marketing' });
const newResourcesTag18 = new ResourcesTag({ name: 'development' });
const newResourcesTag19 = new ResourcesTag({ name: 'programming' });
const newResourcesTag20 = new ResourcesTag({ name: 'mathematics' });
const newResourcesTag21 = new ResourcesTag({ name: 'aI' });
const newResourcesTag22 = new ResourcesTag({ name: 'machine learning' });
const newResourcesTag23 = new ResourcesTag({ name: 'blockchain' });
const newResourcesTag24 = new ResourcesTag({ name: 'software engineering' });
const newResourcesTag25 = new ResourcesTag({ name: 'technical leadership' });
const newResourcesTag26 = new ResourcesTag({ name: 'Information security' });
const newResourcesTag27 = new ResourcesTag({ name: 'machine Learning' });
const newResourcesTag28 = new ResourcesTag({ name: 'mooc' });
const newResourcesTag29 = new ResourcesTag({ name: 'startup ideas' });
const newResourcesTag30 = new ResourcesTag({ name: 'non-Fiction book' });
const newResourcesTag31 = new ResourcesTag({ name: 'management' });
const newResourcesTag32 = new ResourcesTag({ name: 'self-improvement' });
const newResourcesTag33 = new ResourcesTag({ name: 'books' });
const newResourcesTag34 = new ResourcesTag({ name: 'biographies' });
const newResourcesTag35 = new ResourcesTag({ name: 'pmf' });
const newResourcesTag36 = new ResourcesTag({ name: 'gtm' });
const newResourcesTag37 = new ResourcesTag({ name: 'sas mindfulness' });
const newResourcesTag38 = new ResourcesTag({ name: 'business books' });
const newResourcesTag39 = new ResourcesTag({ name: 'social anxiety' });
const newResourcesTag40 = new ResourcesTag({ name: 'human behaviour' });
const newResourcesTag41 = new ResourcesTag({ name: 'digital world' });
const newResourcesTag42 = new ResourcesTag({ name: 'video drm' });
const newResourcesTag43 = new ResourcesTag({ name: 'oudcl' });
const newResourcesTag44 = new ResourcesTag({ name: 'leadership' });
const newResourcesTag45 = new ResourcesTag({ name: 'pmf' });
const newResourcesTag46 = new ResourcesTag({ name: 'pcf' });
const newResourcesTag47 = new ResourcesTag({ name: 'growth' });
const newResourcesTag48 = new ResourcesTag({ name: 'india specific problems' });
const newResourcesTag49 = new ResourcesTag({ name: 'education' });
const newResourcesTag50 = new ResourcesTag({ name: 'technology' });
const newResourcesTag51 = new ResourcesTag({ name: 'data science' });
const newResourcesTag52 = new ResourcesTag({ name: 'differential programming' });
const newResourcesTag53 = new ResourcesTag({ name: 'drones' });
const newResourcesTag54 = new ResourcesTag({ name: 'comp vision' });
const newResourcesTag55 = new ResourcesTag({ name: 'behavioral economics' });
const newResourcesTag56 = new ResourcesTag({ name: 'Payments' });
const newResourcesTag57 = new ResourcesTag({ name: 'next billion' });
const newResourcesTag58 = new ResourcesTag({ name: 'users' });
const newResourcesTag59 = new ResourcesTag({ name: 'programming' });
const newResourcesTag60 = new ResourcesTag({ name: 'ruby' });
const newResourcesTag61 = new ResourcesTag({ name: 'ruby on rails' });
const newResourcesTag62 = new ResourcesTag({ name: 'web application' });
const newResourcesTag63 = new ResourcesTag({ name: 'api development' });
const newResourcesTag64 = new ResourcesTag({ name: 'consumer psychology' });
const newResourcesTag65 = new ResourcesTag({ name: 'product building' });
const newResourcesTag66 = new ResourcesTag({ name: 'mindfulness' });
const newResourcesTag67 = new ResourcesTag({ name: 'users psychology' });
const newResourcesTag68 = new ResourcesTag({ name: 'deep learning' });
const newResourcesTag69 = new ResourcesTag({ name: 'python' });
const newResourcesTag70 = new ResourcesTag({ name: 'angularJS' });
const newResourcesTag71 = new ResourcesTag({ name: 'engineering team' });
const newResourcesTag72 = new ResourcesTag({ name: 'competition' });
const newResourcesTag73 = new ResourcesTag({ name: 'beginner Tech course' });
const newResourcesTag74 = new ResourcesTag({ name: 'design' });
const newResourcesTag75 = new ResourcesTag({ name: 'shared mobility' });
const newResourcesTag76 = new ResourcesTag({ name: 'Politics' });
const newResourcesTag77 = new ResourcesTag({ name: 'games' });
const newResourcesTag78 = new ResourcesTag({ name: 'recently incentive systems' });
const newResourcesTag79 = new ResourcesTag({ name: 'open-source software' });
const newResourcesTag80 = new ResourcesTag({ name: 'best practice' });
const newResourcesTag81 = new ResourcesTag({ name: 'Web dev' });
const newResourcesTag82 = new ResourcesTag({ name: '' });
const newResourcesTag83 = new ResourcesTag({ name: 'mL' });
const newResourcesTag84 = new ResourcesTag({ name: 'product dev' });
const newResourcesTag85 = new ResourcesTag({ name: 'arsenal football club' });
const newResourcesTag86 = new ResourcesTag({ name: 'user onboarding' });
const newResourcesTag87 = new ResourcesTag({ name: 'productivity' });
const newResourcesTag88 = new ResourcesTag({ name: 'parenting' });
const newResourcesTag89 = new ResourcesTag({ name: 'reddit' });
const newResourcesTag90 = new ResourcesTag({ name: 'researching' });

function saveAllFeedbackTags() {
  newFeedbackTag1.save();
  newFeedbackTag2.save();
  newFeedbackTag3.save();
  newFeedbackTag4.save();
  newFeedbackTag5.save();
  newFeedbackTag6.save();
  newFeedbackTag7.save();
  newFeedbackTag8.save();
  newFeedbackTag9.save();
  newFeedbackTag10.save();
  newFeedbackTag11.save();
  newFeedbackTag12.save();
  newFeedbackTag13.save();
  newFeedbackTag14.save();
  newFeedbackTag15.save();
  newFeedbackTag16.save();
  newFeedbackTag17.save();
  newFeedbackTag18.save();
  newFeedbackTag19.save();
  newFeedbackTag20.save();
  newFeedbackTag21.save();
  newFeedbackTag22.save();
  newFeedbackTag23.save();
  newFeedbackTag24.save();
  newFeedbackTag25.save();
  newFeedbackTag26.save();
  newFeedbackTag27.save();
  newFeedbackTag28.save();
  newFeedbackTag29.save();
  newFeedbackTag30.save();
  newFeedbackTag31.save();
  newFeedbackTag32.save();
  newFeedbackTag33.save();
  newFeedbackTag34.save();
  newFeedbackTag35.save();
  newFeedbackTag36.save();
  newFeedbackTag37.save();
  newFeedbackTag38.save();
  newFeedbackTag39.save();
  newFeedbackTag40.save();
  newFeedbackTag41.save();
  newFeedbackTag42.save();
  newFeedbackTag43.save();
  newFeedbackTag44.save();
  newFeedbackTag45.save();
  newFeedbackTag46.save();
  newFeedbackTag47.save();
  newFeedbackTag48.save();
  newFeedbackTag49.save();
  newFeedbackTag50.save();
  newFeedbackTag51.save();
  newFeedbackTag52.save();
  newFeedbackTag53.save();
  newFeedbackTag54.save();
  newFeedbackTag55.save();
  newFeedbackTag56.save();
  newFeedbackTag57.save();
  newFeedbackTag58.save();
  newFeedbackTag59.save();
  newFeedbackTag60.save();
  newFeedbackTag61.save();
  newFeedbackTag62.save();
  newFeedbackTag63.save();
  newFeedbackTag64.save();
  newFeedbackTag65.save();
  newFeedbackTag66.save();
  newFeedbackTag67.save();
  newFeedbackTag68.save();
  newFeedbackTag69.save();
  newFeedbackTag70.save();
  newFeedbackTag71.save();
  newFeedbackTag72.save();
  newFeedbackTag73.save();
  newFeedbackTag74.save();
  newFeedbackTag75.save();
  newFeedbackTag76.save();
  newFeedbackTag77.save();
  newFeedbackTag78.save();
  newFeedbackTag79.save();
  newFeedbackTag80.save();
  newFeedbackTag81.save();
  newFeedbackTag82.save();
  newFeedbackTag83.save();
  newFeedbackTag84.save();
  newFeedbackTag85.save();
  newFeedbackTag86.save();
  newFeedbackTag87.save();
  newFeedbackTag88.save();
  newFeedbackTag89.save();
  newFeedbackTag90.save();
  newFeedbackTag91.save();
  newFeedbackTag92.save();
  newFeedbackTag93.save();
  newFeedbackTag94.save();
  newFeedbackTag95.save();
  newFeedbackTag96.save();
  newFeedbackTag97.save();
  newFeedbackTag98.save();
  newFeedbackTag99.save();
  newFeedbackTag100.save();
  newFeedbackTag101.save();
  newFeedbackTag102.save();
  newFeedbackTag103.save();
  newFeedbackTag104.save();
  newFeedbackTag105.save();
  newFeedbackTag106.save();
  newFeedbackTag107.save();
  newFeedbackTag108.save();
  newFeedbackTag109.save();
  newFeedbackTag110.save();
  newFeedbackTag111.save();
  newFeedbackTag112.save();
  newFeedbackTag113.save();
}

function saveAllIntroductionTags() {
  newIntroductionTag1.save();
  newIntroductionTag2.save();
  newIntroductionTag3.save();
  newIntroductionTag4.save();
  newIntroductionTag5.save();
  newIntroductionTag6.save();
  newIntroductionTag7.save();
  newIntroductionTag8.save();
  newIntroductionTag9.save();
  newIntroductionTag10.save();
  newIntroductionTag11.save();
  newIntroductionTag12.save();
  newIntroductionTag13.save();
  newIntroductionTag14.save();
  newIntroductionTag15.save();
  newIntroductionTag16.save();
  newIntroductionTag17.save();
  newIntroductionTag18.save();
  newIntroductionTag19.save();
  newIntroductionTag20.save();
  newIntroductionTag21.save();
  newIntroductionTag22.save();
  newIntroductionTag23.save();
  newIntroductionTag24.save();
  newIntroductionTag25.save();
  newIntroductionTag26.save();
  newIntroductionTag27.save();
  newIntroductionTag28.save();
  newIntroductionTag29.save();
  newIntroductionTag30.save();
  newIntroductionTag31.save();
  newIntroductionTag32.save();
  newIntroductionTag33.save();
  newIntroductionTag34.save();
  newIntroductionTag35.save();
  newIntroductionTag36.save();
  newIntroductionTag37.save();
  newIntroductionTag38.save();
  newIntroductionTag39.save();
  newIntroductionTag40.save();
  newIntroductionTag41.save();
  newIntroductionTag42.save();
  newIntroductionTag43.save();
  newIntroductionTag44.save();
  newIntroductionTag45.save();
  newIntroductionTag46.save();
  newIntroductionTag47.save();
  newIntroductionTag48.save();
  newIntroductionTag49.save();
  newIntroductionTag50.save();
  newIntroductionTag51.save();
  newIntroductionTag52.save();
  newIntroductionTag53.save();
  newIntroductionTag54.save();
  newIntroductionTag55.save();
  newIntroductionTag56.save();
  newIntroductionTag57.save();
  newIntroductionTag58.save();
  newIntroductionTag59.save();
  newIntroductionTag60.save();
  newIntroductionTag61.save();
}


function saveAllResourcesTags() {
  newResourcesTag1.save();
  newResourcesTag2.save();
  newResourcesTag3.save();
  newResourcesTag4.save();
  newResourcesTag5.save();
  newResourcesTag6.save();
  newResourcesTag7.save();
  newResourcesTag8.save();
  newResourcesTag9.save();
  newResourcesTag10.save();
  newResourcesTag11.save();
  newResourcesTag12.save();
  newResourcesTag13.save();
  newResourcesTag14.save();
  newResourcesTag15.save();
  newResourcesTag16.save();
  newResourcesTag17.save();
  newResourcesTag18.save();
  newResourcesTag19.save();
  newResourcesTag20.save();
  newResourcesTag21.save();
  newResourcesTag22.save();
  newResourcesTag23.save();
  newResourcesTag24.save();
  newResourcesTag25.save();
  newResourcesTag26.save();
  newResourcesTag27.save();
  newResourcesTag28.save();
  newResourcesTag29.save();
  newResourcesTag30.save();
  newResourcesTag31.save();
  newResourcesTag32.save();
  newResourcesTag33.save();
  newResourcesTag34.save();
  newResourcesTag35.save();
  newResourcesTag36.save();
  newResourcesTag37.save();
  newResourcesTag38.save();
  newResourcesTag39.save();
  newResourcesTag40.save();
  newResourcesTag41.save();
  newResourcesTag42.save();
  newResourcesTag43.save();
  newResourcesTag44.save();
  newResourcesTag45.save();
  newResourcesTag46.save();
  newResourcesTag47.save();
  newResourcesTag48.save();
  newResourcesTag49.save();
  newResourcesTag50.save();
  newResourcesTag51.save();
  newResourcesTag52.save();
  newResourcesTag53.save();
  newResourcesTag54.save();
  newResourcesTag55.save();
  newResourcesTag56.save();
  newResourcesTag57.save();
  newResourcesTag58.save();
  newResourcesTag59.save();
  newResourcesTag60.save();
  newResourcesTag61.save();
  newResourcesTag62.save();
  newResourcesTag63.save();
  newResourcesTag64.save();
  newResourcesTag65.save();
  newResourcesTag66.save();
  newResourcesTag67.save();
  newResourcesTag68.save();
  newResourcesTag69.save();
  newResourcesTag70.save();
  newResourcesTag71.save();
  newResourcesTag72.save();
  newResourcesTag73.save();
  newResourcesTag74.save();
  newResourcesTag75.save();
  newResourcesTag76.save();
  newResourcesTag77.save();
  newResourcesTag78.save();
  newResourcesTag79.save();
  newResourcesTag80.save();
  newResourcesTag81.save();
  newResourcesTag82.save();
  newResourcesTag83.save();
  newResourcesTag84.save();
  newResourcesTag85.save();
  newResourcesTag86.save();
  newResourcesTag87.save();
  newResourcesTag88.save();
  newResourcesTag89.save();
  newResourcesTag90.save();
}

module.exports = {
  init: () => {
    ResourcesTag.count((err, number) => {
      if (number === 0) {
        saveAllFeedbackTags();
        saveAllIntroductionTags();
        saveAllResourcesTags();
        // save
      }
    });
  },
};
